# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'player_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Player(object):
    def setupUi(self, Player):
        Player.setObjectName("Player")
        Player.resize(1200, 722)
        self.Background = QtWidgets.QLabel(Player)
        self.Background.setGeometry(QtCore.QRect(10, 10, 840, 630))
        self.Background.setText("")
        self.Background.setObjectName("Background")
        self.Screen = QtWidgets.QLabel(Player)
        self.Screen.setGeometry(QtCore.QRect(10, 10, 591, 321))
        self.Screen.setObjectName("Screen")
        self.Slider = QtWidgets.QSlider(Player)
        self.Slider.setGeometry(QtCore.QRect(10, 650, 840, 20))
        self.Slider.setOrientation(QtCore.Qt.Horizontal)
        self.Slider.setObjectName("Slider")
        self.horizontalLayoutWidget = QtWidgets.QWidget(Player)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 680, 841, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.FullScreenBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FullScreenBtn.sizePolicy().hasHeightForWidth())
        self.FullScreenBtn.setSizePolicy(sizePolicy)
        self.FullScreenBtn.setText("")
        self.FullScreenBtn.setObjectName("FullScreenBtn")
        self.horizontalLayout.addWidget(self.FullScreenBtn)
        self.PlayBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PlayBtn.setText("")
        self.PlayBtn.setObjectName("PlayBtn")
        self.horizontalLayout.addWidget(self.PlayBtn)
        self.PauseBtn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.PauseBtn.setText("")
        self.PauseBtn.setObjectName("PauseBtn")
        self.horizontalLayout.addWidget(self.PauseBtn)
        self.PlaySpeedBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.PlaySpeedBox.setObjectName("PlaySpeedBox")
        self.horizontalLayout.addWidget(self.PlaySpeedBox)
        self.SubtitleBox = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.SubtitleBox.setObjectName("SubtitleBox")
        self.horizontalLayout.addWidget(self.SubtitleBox)
        self.ExitFullScreenBtn = QtWidgets.QPushButton(Player)
        self.ExitFullScreenBtn.setGeometry(QtCore.QRect(720, 0, 93, 28))
        self.ExitFullScreenBtn.setText("")
        self.ExitFullScreenBtn.setObjectName("ExitFullScreenBtn")
        self.verticalLayoutWidget = QtWidgets.QWidget(Player)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(870, 0, 321, 711))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.CategoryLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CategoryLabel.sizePolicy().hasHeightForWidth())
        self.CategoryLabel.setSizePolicy(sizePolicy)
        self.CategoryLabel.setObjectName("CategoryLabel")
        self.horizontalLayout_3.addWidget(self.CategoryLabel)
        self.CategoryComboBox = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.CategoryComboBox.setObjectName("CategoryComboBox")
        self.horizontalLayout_3.addWidget(self.CategoryComboBox)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.SearchIcon = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SearchIcon.sizePolicy().hasHeightForWidth())
        self.SearchIcon.setSizePolicy(sizePolicy)
        self.SearchIcon.setText("")
        self.SearchIcon.setObjectName("SearchIcon")
        self.horizontalLayout_2.addWidget(self.SearchIcon)
        self.SearchKeyword = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.SearchKeyword.setObjectName("SearchKeyword")
        self.horizontalLayout_2.addWidget(self.SearchKeyword)
        self.SearchButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SearchButton.setText("")
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout_2.addWidget(self.SearchButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.PlayList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.PlayList.setObjectName("PlayList")
        self.verticalLayout.addWidget(self.PlayList)
        self.HistoryList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.HistoryList.setObjectName("HistoryList")
        self.verticalLayout.addWidget(self.HistoryList)
        self.SubtitleText = QtWidgets.QLabel(Player)
        self.SubtitleText.setGeometry(QtCore.QRect(91, 564, 691, 61))
        self.SubtitleText.setText("")
        self.SubtitleText.setAlignment(QtCore.Qt.AlignCenter)
        self.SubtitleText.setObjectName("SubtitleText")

        self.retranslateUi(Player)
        QtCore.QMetaObject.connectSlotsByName(Player)

    def retranslateUi(self, Player):
        _translate = QtCore.QCoreApplication.translate
        Player.setWindowTitle(_translate("Player", "MyPlayer"))
        self.Screen.setText(_translate("Player", "TextLabel"))
        self.CategoryLabel.setText(_translate("Player", "Category:"))
